# Generated by Django 2.2.3 on 2019-09-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='stores',
            field=models.ManyToManyField(to='main_app.Store'),
        ),
    ]
